/* ============================================================
   SIP & PLAY — COMPLETE BRAND EQUIPMENT DATASET
   Brands: EVEBOT, INNOSONG, T&Z, LEHEHE
   All specifications, model variants, and images derived from
   official factory catalogues, spec sheets, and CAD renders.
   ============================================================ */

var brandProducts = [
  // ============================================================
  // BRAND 1: EVEBOT (亿瓦) — BEVERAGE & EDIBLE PRINTING SYSTEMS
  // ============================================================
  {
    id: "brand-evobot-1",
    sku: "EB-FC1",
    name: "EVEBOT EB-FC1 Full-Color Commercial Coffee & Food Printer",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Coffee Art & Food Printers",
    power: "60W (AC 100–240V 50/60Hz)",
    powerKw: "0.06",
    voltage: "100-240V",
    dimensions: "270 × 340 × 410 mm",
    capacity: "600–800 cups / FB3 multi-color cartridge",
    origin: "China",
    material: "Full metal chassis + food-grade cartridge system",
    description: "Commercial high-resolution full-color edible inkjet coffee and food printer. Prints custom multi-color images, selfies, logos, and latte art onto coffee foam, milk tea, beer foam, macarons, cakes, and pastries in 30–50 seconds with 600 DPI precision.",
    otherSpecifications: "Print Resolution: 600 DPI | Print Speed: 30–50s/cup | Cup Diameter: 4–10 cm | Cup Height: 5–18 cm | Cartridge: FB3 Multi-Color Edible Ink (Food Contact Certified) | Interface: Independent Wi-Fi & Web-App (QR code scan upload, no app installation required) | Net Weight: 12 kg | Accessories: Macaron Riser plate supported",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/evobot/Pro%20Coffee%20printer.jpg.jpeg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/Pro Coffee printer.jpg.jpeg",
    imageVerified: true
  },
  {
    id: "brand-evobot-2",
    sku: "EB-Pro",
    name: "EVEBOT EB-Pro High-Speed Single-Color Commercial Coffee Printer",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Coffee Art & Food Printers",
    power: "60W (AC 100–240V 50/60Hz)",
    powerKw: "0.06",
    voltage: "100-240V",
    dimensions: "270 × 340 × 410 mm",
    capacity: "800–1000 cups / FB2 brown edible cartridge",
    origin: "China",
    material: "Full metal chassis + food-grade edible cartridge",
    description: "High-speed commercial single-color edible coffee printer engineered for peak café rushes. Produces crisp brown latte art and logo prints in just 5–15 seconds per cup at 600 DPI resolution.",
    otherSpecifications: "Print Resolution: 600 DPI | Ultra-Fast Print Speed: 5–15s/cup | Cup Diameter: 4–10 cm | Cup Height: 5–18 cm | Cartridge: FB2 Coffee-Brown Edible Ink Cartridge | Interface: Wi-Fi + QR scan web-app | Net Weight: 12 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/evobot/White.jpg.jpeg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/White.jpg.jpeg",
    imageVerified: true
  },
  {
    id: "brand-evobot-3",
    sku: "EB-FT4",
    name: "EVEBOT EB-FT4 Classical Commercial Beverage Printer",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Coffee Art & Food Printers",
    power: "60W (AC 100–240V 50/60Hz)",
    powerKw: "0.06",
    voltage: "100-240V",
    dimensions: "270 × 340 × 410 mm",
    capacity: "600–800 cups / cartridge",
    origin: "China",
    material: "All-Steel Commercial Body",
    description: "Classical series commercial coffee and beverage surface printer. Reliable standalone operation for continuous printing of high-contrast graphics and text onto beverages, foam, and culinary desserts.",
    otherSpecifications: "Print Resolution: 600 DPI | Print Speed: 20–30s/cup | Cup Diameter: 4–10 cm | Cup Height: 5–18 cm | Interface: Standalone Wi-Fi Access Point | Net Weight: 12 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/evobot/Black.jpg.jpeg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/Black.jpg.jpeg",
    imageVerified: true
  },
  {
    id: "brand-evobot-4",
    sku: "EB-FM1",
    name: "EVEBOT EB-FM1 Mini Desktop Beverage & Food Printer",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Coffee Art & Food Printers",
    power: "60W (AC 100–240V 50/60Hz)",
    powerKw: "0.06",
    voltage: "100-240V",
    dimensions: "250 × 300 × 380 mm",
    capacity: "600–800 cups / cartridge",
    origin: "China",
    material: "Compact Lightweight Composite & Aluminum Housing",
    description: "Space-saving compact desktop coffee printer designed for boutique beverage stations, cocktail bars, and pop-up events requiring high-precision beverage branding in a minimal footprint.",
    otherSpecifications: "Print Resolution: 600 DPI | Print Speed: 15–20s/cup | Cup Diameter: 4–10 cm | Cup Height: 5–18 cm | Net Weight: 10 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/evobot/White.jpg.jpeg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/White.jpg.jpeg",
    imageVerified: true
  },
  {
    id: "brand-evobot-5",
    sku: "PrintPen",
    name: "EVEBOT PrintPen Portable Handheld Edible Printer (Bluetooth)",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Portable Food Printers",
    power: "1200mAh 7.4V Rechargeable Li-ion (Type-C)",
    powerKw: "",
    voltage: "7.4V DC",
    dimensions: "174 × 53 × 30 mm",
    capacity: "Up to 2,000 standard prints per charge",
    origin: "China",
    material: "Ergonomic CNC Aluminum Housing",
    description: "Ultra-portable handheld edible printer for customizing coffee foam, baked goods, plates, toast, macarons, and textured culinary surfaces. Features wireless Bluetooth 4.2 connectivity and custom graphic upload via Evebot OS.",
    otherSpecifications: "Print Width: 26 mm (Length up to 100 cm) | Resolution: 300 DPI | Battery: 1200 mAh (Type-C charging port) | Weight: 255g (with cartridge) | Cartridge: Certified food-grade edible ink | Connectivity: Bluetooth 4.2 / Wi-Fi | App: Evebot OS (iOS / Android)",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/evobot/PrintPen%20Page/P1.jpg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/PrintPen Page/P1.jpg",
    imageVerified: true
  },
  {
    id: "brand-evobot-6",
    sku: "FB3-INK",
    name: "EVEBOT FB3 Multi-Color Food-Grade Edible Ink Cartridge",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Consumables & Accessories",
    power: "Passive Consumable",
    powerKw: "",
    voltage: "",
    dimensions: "80 × 50 × 35 mm",
    capacity: "600–800 full-color beverage prints",
    origin: "China",
    material: "Food Contact Grade Polypropylene & Certified Edible Formulation",
    description: "Official multi-color edible ink replacement cartridge for EVEBOT EB-FC1 food and beverage printer. Compliant with international food hygiene, FDA, and SGS contact safety standards.",
    otherSpecifications: "Ink Colors: Full Spectrum Cyan/Magenta/Yellow blend | Print Yield: 600–800 standard beverage cups | Safety: SGS, FDA Food Safety Certified | Shelf Life: 12 months sealed",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/evobot/PrintPen%20Page/P6.jpg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/PrintPen Page/P6.jpg",
    imageVerified: true
  },
  {
    id: "brand-evobot-7",
    sku: "FB2-INK",
    name: "EVEBOT FB2 Coffee-Brown Food-Grade Edible Ink Cartridge",
    brand: "EVEBOT",
    category: "Specialty Beverage Equipment",
    subCategory: "Consumables & Accessories",
    power: "Passive Consumable",
    powerKw: "",
    voltage: "",
    dimensions: "80 × 50 × 35 mm",
    capacity: "800–1,000 coffee prints",
    origin: "China",
    material: "Food Contact Certified Formulation",
    description: "Official single-color coffee-brown edible ink cartridge designed for EB-Pro high-speed printer. Natural roasted caramel-brown tone for authentic latte art replication.",
    otherSpecifications: "Color: Rich Coffee Brown | Yield: 800–1000 prints | Fast Drying: 1–2 seconds | Certified Food Grade",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/evobot/PrintPen%20Page/P8.jpg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/evobot/PrintPen Page/P8.jpg",
    imageVerified: true
  },

  // ============================================================
  // BRAND 2: INNOSONG (智松科技) — COMMERCIAL ESPRESSO & GRINDERS
  // ============================================================
  {
    id: "brand-innosong-1",
    sku: "ZS3101",
    name: "INNOSONG ZS3101 Commercial 1-Group Dual Boiler Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "1-Group Espresso Machines",
    power: "2400W (220V / 50Hz)",
    powerKw: "2.40",
    voltage: "220V",
    dimensions: "361 × 440 × 376 mm",
    capacity: "0.55L Coffee Boiler + 1.0L Steam Boiler + 2.5L Water Tank",
    origin: "China",
    material: "Mirror Stainless Steel + Solid Walnut Wood Accents",
    description: "Heavy-duty commercial 1-group dual boiler espresso machine with independent PID temperature control. Equipped with a saturated 58mm group, dual extraction and steam pressure gauges, manual wood lever steam control, and flexible dual water supply (removable 2.5L tank or direct plumbed).",
    otherSpecifications: "Group: 1 Group Commercial | Boilers: 0.55L Stainless Coffee Boiler + 1.0L Steam Boiler | Pump: Italy 15-bar Vibration Pump (ZS3101) / Italy 9-bar Rotary Vane Pump (ZS3101A) | Portafilter: 58mm Commercial Brass/Stainless | Temp Control: Dual PID | Gauges: Independent Coffee & Steam Gauges | Net Weight: 28 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/insong/2.2563.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/2.2563.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-2",
    sku: "ZS3105",
    name: "INNOSONG ZS3105 Saturated Group Commercial 1-Group Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "1-Group Espresso Machines",
    power: "2400W (220V / 50Hz)",
    powerKw: "2.40",
    voltage: "220V",
    dimensions: "330 × 485 × 390 mm",
    capacity: "0.55L Saturated Coffee Boiler + 1.0L Steam Boiler",
    origin: "China",
    material: "Brushed & Polished Stainless Steel + Walnut Levers",
    description: "Precision saturated grouphead commercial 1-group espresso machine with rotary pump configuration (ZS3105A). Features paddle/lever steam engagement, grouphead top pressure gauge, PID thermal stability, and solid wood ergonomic portafilter.",
    otherSpecifications: "Group: 1 Saturated Group | Boilers: 0.55L Brew + 1.0L Steam | Pump: Italy 9-bar Rotary Pump (ZS3105A) / Vibration Pump (ZS3105) | Pressure: Grouphead Pressure Gauge + System Gauges | Control: Electronic Push-Button + Manual Lever | Net Weight: 26 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/insong/1.2438.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/1.2438.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-3",
    sku: "ZS3102",
    name: "INNOSONG ZS3102 Commercial 1-Group Dual Boiler Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "1-Group Espresso Machines",
    power: "2400W (220V / 50Hz)",
    powerKw: "2.40",
    voltage: "220V",
    dimensions: "329 × 540 × 410 mm",
    capacity: "0.55L Coffee Boiler + 1.0L Steam Boiler + 2.5L Water Tank",
    origin: "China",
    material: "Matte Black & Stainless Steel Construction",
    description: "Compact commercial single group espresso machine engineered for specialty coffee bars, boutique restaurants, and executive suites requiring continuous steam performance and precise extraction temperature.",
    otherSpecifications: "Boilers: 0.55L Coffee + 1.0L Steam | Pump: Italy 15-bar Vib / 9-bar Rotary (ZS3102A) | Portafilter: 58mm | Net Weight: 27 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/insong/1.2598.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/1.2598.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-4",
    sku: "ZS3202",
    name: "INNOSONG ZS3202 Commercial 2-Group Multi-Boiler Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "2-Group Espresso Machines",
    power: "4200W (220V / 50Hz)",
    powerKw: "4.20",
    voltage: "220V",
    dimensions: "714 × 516 × 463 mm",
    capacity: "Dual 0.55L Coffee Boilers + 9.5L Heavy-Duty Steam Boiler",
    origin: "China",
    material: "Heavy-Gauge Stainless Steel & Matte Black with Walnut Actuators",
    description: "High-volume commercial 2-group multi-boiler espresso machine featuring dual HD LCD digital interfaces for shot timing and parameter programming, dual 4-hole cool-touch steam wands with wood lever actuation, and high-capacity 9.5L steam boiler.",
    otherSpecifications: "Groups: 2 Commercial Groups | Boilers: Dual 0.55L Saturated Coffee Boilers + 9.5L Service Boiler | Pump: Italy 9-bar Commercial Rotary Vane Pump | Displays: Dual HD LCD Digital Screens (Shot timers & temperature) | Steam: Dual Ergonomic Wood Levers | Net Weight: 55 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/insong/41.2604.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/41.2604.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-5",
    sku: "ZS3201",
    name: "INNOSONG ZS3201 Commercial 2-Group Multi-Boiler Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "2-Group Espresso Machines",
    power: "4200W (220V / 50Hz)",
    powerKw: "4.20",
    voltage: "220V",
    dimensions: "740 × 560 × 468.5 mm",
    capacity: "Dual 0.55L Coffee Boilers + 10.5L Heavy-Duty Steam Boiler",
    origin: "China",
    material: "Mirror Polished Stainless Steel Chassis",
    description: "Flagship commercial 2-group multi-boiler machine with 10.5L high-capacity steam boiler, dual independent flowmeters, saturated brewing groups, and multi-zone PID thermal management.",
    otherSpecifications: "Groups: 2 Commercial Groups | Boilers: Dual 0.55L Coffee + 10.5L Steam | Pump: Commercial Rotary Pump | Display: Dual LCD Screens | Net Weight: 58 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/insong/41.2604.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/41.2604.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-6",
    sku: "ZS3001",
    name: "INNOSONG ZS3001 Prosumer Dual-Thermoblock Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "Compact Espresso Machines",
    power: "3000W (220V / 50Hz)",
    powerKw: "3.00",
    voltage: "220V",
    dimensions: "220 × 475 × 346 mm",
    capacity: "1.8L Removable Water Tank",
    origin: "China",
    material: "Brushed Stainless Steel + Wood Handle Portafilter",
    description: "Compact prosumer espresso machine featuring dual rapid-heat thermoblocks, dual vibration pumps for simultaneous brewing and steaming, commercial 58mm portafilter, and PID temperature stability.",
    otherSpecifications: "Heating: Dual Thermoblock System | Pump: Dual Italy Vibration Pumps | Portafilter: 58mm Commercial Brass | Water Tank: 1.8L | Net Weight: 14.5 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/insong/2.2563.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/2.2563.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-7",
    sku: "ZS3002",
    name: "INNOSONG ZS3002 Prosumer Single-Thermoblock Espresso Machine",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "Compact Espresso Machines",
    power: "1550W (220V / 50Hz)",
    powerKw: "1.55",
    voltage: "220V",
    dimensions: "220 × 475 × 346 mm",
    capacity: "1.8L Removable Water Tank",
    origin: "China",
    material: "Stainless Steel Body & 58mm Commercial Portafilter",
    description: "Energy-efficient single thermoblock prosumer espresso machine with rapid thermal warm-up, precision 58mm portafilter extraction, and PID temperature regulation.",
    otherSpecifications: "Heating: Single High-Efficiency Thermoblock | Pump: Italy Vibration Pump | Portafilter: 58mm | Water Tank: 1.8L | Weight: 13.5 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/insong/4.2578.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/insong/4.2578.png",
    imageVerified: true
  },
  {
    id: "brand-innosong-8",
    sku: "ZS9001",
    name: "INNOSONG ZS9001 Commercial On-Demand Coffee Grinder (1kg Hopper)",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "Coffee Grinders",
    power: "350W (220V / 50Hz)",
    powerKw: "0.35",
    voltage: "220V",
    dimensions: "150 × 150 × 510 mm",
    capacity: "1000g Large Bean Hopper",
    origin: "China",
    material: "Die-Cast Aluminum & SUS420 Hardened Steel Flat Burrs",
    description: "High-throughput commercial on-demand espresso grinder with 64mm SUS420 hardened stainless steel flat burrs, 1000g large hopper, 18-step micrometric collar, and touch digital dose timer.",
    otherSpecifications: "Burr Size: 64mm SUS420 Flat Burrs | Speed: 3500 RPM | Hopper Capacity: 1.0 kg | Adjustment: 18-Step Precision | Net Weight: 9.0 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "images/category-placeholder.jpg",
    imageStatus: "placeholder-category",
    imageSource: "catalog-spec",
    imageVerified: false
  },
  {
    id: "brand-innosong-9",
    sku: "ZS9002",
    name: "INNOSONG ZS9002 Commercial On-Demand Precision Coffee Grinder (Titanium Burrs)",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "Coffee Grinders",
    power: "350W (220V / 50Hz)",
    powerKw: "0.35",
    voltage: "220V",
    dimensions: "252 × 210 × 420 mm",
    capacity: "500g Bean Hopper",
    origin: "China",
    material: "Die-Cast Aluminum & Titanium Coated Flat Burrs",
    description: "Commercial on-demand espresso grinder equipped with 64mm Titanium flat burrs, 18-step precision grind adjustment dial, LED/LCD touch display for programmable single and double dose timing.",
    otherSpecifications: "Burr Diameter: 64mm Titanium Flat Burrs | Motor Speed: 3500 RPM | Grinding Speed: 1.8–2.5 g/s | Hopper: 500g UV-resistant | Display: LCD Touchscreen Dose Timer | Net Weight: 8.5 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "images/category-placeholder.jpg",
    imageStatus: "placeholder-category",
    imageSource: "catalog-spec",
    imageVerified: false
  },
  {
    id: "brand-innosong-10",
    sku: "ZS9003",
    name: "INNOSONG ZS9003 Compact Commercial Precision Coffee Grinder",
    brand: "INNOSONG",
    category: "Commercial Coffee Systems",
    subCategory: "Coffee Grinders",
    power: "350W (220V / 50Hz)",
    powerKw: "0.35",
    voltage: "220V",
    dimensions: "200 × 130 × 350 mm",
    capacity: "250g / 500g Bean Hopper",
    origin: "China",
    material: "Compact Aluminum Alloy & SUS402 Flat Burrs",
    description: "Space-efficient on-demand commercial grinder featuring 64mm SUS402 flat burrs, 9-gear stepped grind dial, and precise digital timed dispensing for specialty café decaf/single-origin stations.",
    otherSpecifications: "Burr Size: 64mm SUS402 Flat Burrs | Speed: 2800 RPM | Hopper: 250g/500g | Settings: 9 Gear Steps | Weight: 7.5 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "images/category-placeholder.jpg",
    imageStatus: "placeholder-category",
    imageSource: "catalog-spec",
    imageVerified: false
  },

  // ============================================================
  // BRAND 3: T&Z / LEHEHE (大正咖啡集团) — TEA BREWERS & MULTI-BOILERS
  // ============================================================
  {
    id: "brand-tz-1",
    sku: "VK-1",
    name: "T&Z Galaxy U8 VK-1 Single-Head Under-Counter Commercial Tea Extraction Machine",
    brand: "T&Z",
    category: "Specialty Beverage Equipment",
    subCategory: "Under-Counter Tea Brewers",
    power: "3500W (220V / 50~60Hz)",
    powerKw: "3.50",
    voltage: "220V",
    dimensions: "420 × 536 × 952 mm (Cut-out: 405 × 500 mm)",
    capacity: "1.0L Extraction Boiler + 6.6L Heat Exchange Boiler",
    origin: "China",
    material: "Full Stainless Steel Multi-Boiler + Die-Cast Countertop Tower",
    description: "Cutting-edge under-counter commercial tea brewer featuring a minimalist countertop tower, Multi-Boiler T3 heating system, 6-stage segmented pulse extraction with 1g precision, 2.8-inch color touchscreen, and real-time parameter control for fresh on-demand tea brewing.",
    otherSpecifications: "System: Multi-Boiler T3 System | Extraction Boiler: 1.0L Stainless | Steam/Heat Exchange Boiler: 6.6L Stainless | Brewing: 6-Stage Segmented Pulse Brewing (1g precision) | Display: 2.8-inch Color Touchscreen with 7 Parameter Buttons (up to 6 formulas) | Pump: Professional Rotary Pump | Safety: Electronic Dry-Boil, Overheat & Overpressure Protections | Drip Tray: Guided cup placement pattern | Colors: Pearl White, Obsidian Black, Sakura Pink, Matcha Green",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/t%20and%20z/VK-2/VK-2/800-4.jpg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/VK-2/VK-2/800-4.jpg",
    imageVerified: true
  },
  {
    id: "brand-tz-2",
    sku: "VK-2",
    name: "T&Z Galaxy U8 VK-2 Dual-Head Under-Counter Commercial Tea Extraction Machine",
    brand: "T&Z",
    category: "Specialty Beverage Equipment",
    subCategory: "Under-Counter Tea Brewers",
    power: "6200W (220V / 50~60Hz)",
    powerKw: "6.20",
    voltage: "220V",
    dimensions: "830 × 536 × 900 mm (Cut-out: 810 × 490 mm)",
    capacity: "Dual 1.0L Extraction Boilers + 11.0L Steam Boiler",
    origin: "China",
    material: "Full Stainless Steel Boilers + Dual Countertop Towers + Integrated Drip Deck",
    description: "Commercial high-output dual-head under-counter tea extraction system. Equipped with dual independent brewing towers, 11L high-volume steam boiler, dual side steam wands, central hot water faucet, and dual 2.8-inch touchscreens with 6-stage segmented pulse extraction.",
    otherSpecifications: "System: Multi-Boiler T3 Dual-Tower System | Extraction Boilers: 2 × 1.0L Stainless | Steam Boiler: 11.0L Stainless | Auxiliary: Dual Steam Levers + Central Hot Water Dispenser | Touchscreens: Dual 2.8-inch Color Displays | Brewing: 6-Stage Segmented Pulse Extraction (1g accuracy) | Rotary Pump: Commercial Heavy-Duty | Colors: Pearl White, Obsidian Black, Pink, Green",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/t%20and%20z/VK-2/VK-2/800-2.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/VK-2/VK-2/800-2.png",
    imageVerified: true
  },
  {
    id: "brand-tz-3",
    sku: "KT3-2A",
    name: "T&Z KT3-2A Commercial Multi-Boiler Semi-Automatic Espresso Machine (Ultimate Version)",
    brand: "T&Z",
    category: "Commercial Coffee Systems",
    subCategory: "2-Group Espresso Machines",
    power: "6200W (220V / 50~60Hz)",
    powerKw: "6.20",
    voltage: "220V",
    dimensions: "920 × 700 × 500 mm (including levers)",
    capacity: "12L Copper Steam Boiler + Dual 1.0L Copper Coffee Boilers",
    origin: "China",
    material: "6mm Solid Aluminum Alloy Body + Snowflake Stainless Steel Deck + Copper Boilers",
    description: "Ultimate edition commercial 2-group espresso machine with Multi-Boiler T3 heating system (±1°C precision). Features a massive 12L copper steam boiler (3500W), dual 1L copper brew boilers (1000W × 2), brass brew head heaters (500W × 2), 0.1s micro-adjustable pre-infusion, dual 5.0-inch touchscreens, and 240 cups/hour output capacity.",
    otherSpecifications: "Boilers: 12L Copper Steam Boiler + 2 × 1L Copper Coffee Boilers + Brass Head Heaters | Temp Control: Multi-Boiler T3 System (±1°C), Independent Steam (115–124°C) and Head (85–98°C) adjustment | Pre-Infusion: 0.1s Micro-Adjustable | Displays: Dual 5.0-inch Touchscreens | Steam: Dual Omnidirectional Cool-Touch Steam Wands with Ergonomic Pull Levers | Water: Hot & Cold Water Anti-Splashing Mixing Valve | Capacity: 240 cups/hour | Net Weight: 76 kg | Colors: Matte Black, White, Red, Green, Clear Back Panel Edition",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/t%20and%20z/Detail%20Desc/Detail%20Desc/KT3-2%20-O%C2%A6T/KT3-2%208.4.165.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/Detail Desc/Detail Desc/KT3-2 -O¦T/KT3-2 8.4.165.png",
    imageVerified: true
  },
  {
    id: "brand-tz-4",
    sku: "KT3-2-STD",
    name: "T&Z KT3-2 Commercial Multi-Boiler Espresso Machine (Standard Stainless Edition)",
    brand: "T&Z",
    category: "Commercial Coffee Systems",
    subCategory: "2-Group Espresso Machines",
    power: "6200W (220V / 50~60Hz)",
    powerKw: "6.20",
    voltage: "220V",
    dimensions: "920 × 700 × 500 mm",
    capacity: "12L Copper Steam Boiler + Dual 1.0L Copper Coffee Boilers",
    origin: "China",
    material: "Mirror Polished Stainless Steel & Aluminum Alloy Construction",
    description: "Standard commercial edition 2-group espresso machine with Multi-Boiler T3 system, high-precision dual pressure gauges, 5.0-inch touchscreen interfaces, and 240 cups/hour production.",
    otherSpecifications: "Boilers: 12L Steam Boiler (3500W) + 2 × 1L Brew Boilers (1000W × 2) | Temperature: Independent PID Temp Adjustment | Pre-Infusion: 0.1s Precision | Output: 240 cups/hour | Net Weight: 76 kg",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/t%20and%20z/Detail%20Desc/Detail%20Desc/KT3-2%20-O%C2%A6T/KT3-2%208.4.166.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/Detail Desc/Detail Desc/KT3-2 -O¦T/KT3-2 8.4.166.png",
    imageVerified: true
  },
  {
    id: "brand-lehehe-1",
    sku: "DZ23-2Y",
    name: "LEHEHE Galaxy U8 DZ23-2Y Embedded Dual-Head Commercial Steam & Hot Water Station",
    brand: "LEHEHE",
    category: "Specialty Beverage Equipment",
    subCategory: "Under-Counter Steam Stations",
    power: "3000W (220V / 50~60Hz)",
    powerKw: "3.00",
    voltage: "220V",
    dimensions: "Host: 373.4 × 229 × 595.5 mm | Faucet: 391.3 × 98 × 438.1 mm (Cut-out: 2 × Ø25mm)",
    capacity: "8.0L Stainless Steel Steam Boiler",
    origin: "China",
    material: "Full Stainless Steel Boiler & Countertop Dispenser Columns",
    description: "Commercial under-counter dual-head continuous steam and hot water station by Dazheng Coffee Group / LEHEHE. Features twin countertop steam arms with built-in precision temperature probes for auto shut-off at target temp, real-time LED temp display, and 4 preset recipe buttons per head.",
    otherSpecifications: "Boiler: 8.0L Stainless Steel Steam Boiler | Power: 3000W High Efficiency | Temperature Range: 118–128°C Adjustable Boiler Temp | Controls: Digital Tube Display per head, 5 keys (4 preset temp stops + 1 continuous steam 'P' key) | Safety: Electronic Dry-Boil, Overheat & Pressure Relief Protection | Certifications: CCC, CE, CB, Food Contact Safety Certified",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: true,
    image: "brands/t%20and%20z/VK-2/VK-2/2.446.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/VK-2/VK-2/2.446.png",
    imageVerified: true
  },
  {
    id: "brand-lehehe-2",
    sku: "DZ23-1Y",
    name: "LEHEHE Galaxy U8 DZ23-1Y Embedded Single-Head Commercial Steam Station",
    brand: "LEHEHE",
    category: "Specialty Beverage Equipment",
    subCategory: "Under-Counter Steam Stations",
    power: "2200W (220V / 50~60Hz)",
    powerKw: "2.20",
    voltage: "220V",
    dimensions: "Host: 373.4 × 229 × 450 mm | Faucet: 391.3 × 98 × 438.1 mm (Cut-out: Ø25mm)",
    capacity: "5.0L Stainless Steel Steam Boiler",
    origin: "China",
    material: "Stainless Steel Boiler & Countertop Dispenser Column",
    description: "Single-head under-counter commercial steam and milk frothing station. Built-in digital temperature probe automatically stops steam when milk reaches target temperature.",
    otherSpecifications: "Boiler: 5.0L Stainless Steel Steam Boiler | Power: 2200W | Temperature Range: 118–128°C | Controls: 4 Preset Temperature Buttons + Manual Continuous Steam Key | Safety: CCC / CE Certified",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/t%20and%20z/VK-2/VK-2/2.448.png",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/VK-2/VK-2/2.448.png",
    imageVerified: true
  },
  {
    id: "brand-tz-5",
    sku: "U8-DECK",
    name: "T&Z Galaxy U8 Countertop Flush-Mount Stainless Drip & Drainage Deck",
    brand: "T&Z",
    category: "Specialty Beverage Equipment",
    subCategory: "Consumables & Accessories",
    power: "Passive Drain Deck",
    powerKw: "",
    voltage: "",
    dimensions: "830 × 536 × 35 mm (Cut-out: 810 × 490 mm)",
    capacity: "Integrated High-Flow Countertop Drainage Connection",
    origin: "China",
    material: "Commercial Grade 304 Stainless Steel",
    description: "Flush-mount stainless steel drip tray deck with guided laser-etched cup alignment patterns and direct drain connection designed for VK-1, VK-2, and DZ23 under-counter beverage systems.",
    otherSpecifications: "Material: 304 Food-Grade Stainless Steel | Feature: Guided alignment pattern for precise cup placement under brew heads | Connection: Standard Commercial Drainage Outlet",
    sourcePage: null,
    confidence: "high",
    sourceLanguage: "en",
    featured: false,
    image: "brands/t%20and%20z/VK-2/VK-2/Installation.jpg",
    imageStatus: "manufacturer-verified",
    imageSource: "brands/t and z/VK-2/VK-2/Installation.jpg",
    imageVerified: true
  }
];

if (typeof window !== 'undefined') {
  window.BRAND_PRODUCTS = brandProducts;
}
