-- ============================================================
-- SIP & PLAY ENTERPRISE PORTAL — SUPABASE DATABASE SCHEMA
-- Execute this script in your Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New Query -> Run
-- ============================================================

-- 1. Create products table with stock management columns
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sku TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  category TEXT NOT NULL,
  sub_category TEXT,
  power TEXT NOT NULL,
  power_kw TEXT,
  dimensions TEXT,
  origin TEXT,
  material TEXT DEFAULT 'AISI 304 High-Tensile Stainless Steel',
  description TEXT,
  image TEXT,
  featured BOOLEAN DEFAULT FALSE,
  stock_qty INTEGER DEFAULT 10,
  stock_status TEXT DEFAULT 'In Stock (Colombo)',
  unit_price_lkr NUMERIC DEFAULT 850000,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Public Read Access (Anyone can browse products in catalogue)
CREATE POLICY "Public Read Products" 
ON public.products 
FOR SELECT 
USING (true);

-- 4. Policy: Full Access For Management Portal
CREATE POLICY "Allow All For Anon Key" 
ON public.products 
FOR ALL 
USING (true)
WITH CHECK (true);

-- 5. Realtime Publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
